name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack

  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npx webpack

      - name: Deploy to Railway
        run: npx railway deploy --api-key ${{ secrets.RAILWAY_API_KEY }}

      - name: Notify on deploy status
        run: npx railway notify --api-key ${{ secrets.RAILWAY_API_KEY }} --status $DEPLOY_STATUS
